import streamlit as st
import tensorflow as tf
import numpy as np
from PIL import Image

# -----------------------------
# Page Configuration
# -----------------------------
st.set_page_config(
    page_title="AI Signature Verification",
    page_icon="✍️",
    layout="centered"
)

# -----------------------------
# Load Model
# -----------------------------
MODEL_PATH = "models/signature_model.keras"

model = tf.keras.models.load_model(MODEL_PATH)

# -----------------------------
# Title
# -----------------------------
st.title("✍️ AI Signature Verification")
st.write("Upload a signature image to check whether it is Genuine or Forged.")

st.divider()

# -----------------------------
# File Upload
# -----------------------------
uploaded_file = st.file_uploader(
    "Upload Signature Image",
    type=["png", "jpg", "jpeg"]
)

# -----------------------------
# Prediction
# -----------------------------
if uploaded_file is not None:

    image = Image.open(uploaded_file).convert("L")

    st.image(
        image,
        caption="Uploaded Signature",
        width=400
    )

    # Resize image
    image = image.resize((128, 128))

    # Convert to numpy
    image_array = np.array(image)

    # Normalize
    image_array = image_array / 255.0

    # Add channel dimension
    image_array = np.expand_dims(image_array, axis=-1)

    # Add batch dimension
    image_array = np.expand_dims(image_array, axis=0)

    # Prediction
    prediction = model.predict(image_array, verbose=0)[0][0]

    # Class mapping:
    # forged = 0
    # genuine = 1

    if prediction >= 0.5:
        result = "GENUINE"
        confidence = prediction * 100
    else:
        result = "FORGED"
        confidence = (1 - prediction) * 100

    st.divider()

    # -----------------------------
    # Result
    # -----------------------------
    st.subheader("Verification Result")

    if result == "GENUINE":
        st.success(f"✅ Signature is {result}")
    else:
        st.error(f"❌ Signature is {result}")

    st.metric(
        label="Confidence",
        value=f"{confidence:.2f}%"
    )

    st.info(
        "This prediction is generated by the trained CNN deep learning model."
    )